-------------------------------------------------------------------------------
---------------------------------- NAMESPACE ----------------------------------
-------------------------------------------------------------------------------
-- local ADDON_NAME, ns = ...
--
-- local Achievement = ns.reward.Achievement
--
-------------------------------------------------------------------------------
------------------------------------- MAP -------------------------------------
-------------------------------------------------------------------------------
--
-- local map = ns.Map({id = nil, settings = true}) -- TODO: Map ID missing
--
-------------------------------------------------------------------------------
--------------------------------- DRAGONRACES ---------------------------------
-------------------------------------------------------------------------------
--
-- map.nodes[10001000] = ns.node.Dragonrace({
--     label = '{quest:76309}',
--     normal = {nil, nil, nil},
--     advanced = {nil, nil, nil},
--     reverse = {nil, nil, nil},
--     rewards = {
--         Achievement({id = 18566, criteria = 1, oneline = true}), -- normal bronze
--         Achievement({id = 18567, criteria = 1, oneline = true}), -- normal silver
--         Achievement({id = 18568, criteria = 1, oneline = true}), -- normal gold
--         Achievement({id = 18569, criteria = 1, oneline = true}), -- advanced bronze
--         Achievement({id = 18570, criteria = 1, oneline = true}), -- advanced silver
--         Achievement({id = 18571, criteria = 1, oneline = true}), -- advanced gold
--         Achievement({id = 18572, criteria = 1, oneline = true}), -- reverse bronze
--         Achievement({id = 18573, criteria = 1, oneline = true}), -- reverse silver
--         Achievement({id = 18574, criteria = 1, oneline = true}) -- reverse gold
--     }
-- }) -- Gilneas Gambit
