-------------------------------------------------------------------------------
---------------------------------- NAMESPACE ----------------------------------
-------------------------------------------------------------------------------
-- local ADDON_NAME, ns = ...
-- local Achievement = ns.reward.Achievement
-------------------------------------------------------------------------------
------------------------------------- MAP -------------------------------------
-------------------------------------------------------------------------------
-- local map = ns.Map({id = nil, settings = true})
-------------------------------------------------------------------------------
--------------------------------- DRAGONRACES ---------------------------------
-------------------------------------------------------------------------------
-- map.nodes[10001000] = ns.node.Dragonrace({
--     label = '{quest:76309}',
--     normal = {nil, nil, nil},
--     advanced = {nil, nil, nil},
--     reverse = {nil, nil, nil},
--     rewards = {
--         Achievement({id = nil, criteria = nil, oneline = true}), -- normal bronze
--         Achievement({id = nil, criteria = nil, oneline = true}), -- normal silver
--         Achievement({id = nil, criteria = nil, oneline = true}), -- normal gold
--         Achievement({id = nil, criteria = nil, oneline = true}), -- advanced bronze
--         Achievement({id = nil, criteria = nil, oneline = true}), -- advanced silver
--         Achievement({id = nil, criteria = nil, oneline = true}), -- advanced gold
--         Achievement({id = nil, criteria = nil, oneline = true}), -- reverse bronze
--         Achievement({id = nil, criteria = nil, oneline = true}), -- reverse silver
--         Achievement({id = nil, criteria = nil, oneline = true}) -- reverse gold
--     }
-- }) -- Gilneas Gambit
