name: Automated Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      lua-version: 5.3

    steps:
      - uses: actions/checkout@v2

      - name: Install lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ env.lua-version }}

      - name: Install luarocks v3
        run: |
          wget https://luarocks.org/releases/luarocks-3.7.0.tar.gz
          tar zxpf luarocks-3.7.0.tar.gz
          cd luarocks-3.7.0
          ./configure && make && sudo make install

      # The lua-format library takes a while to compile, so we cache it
      # Update the YYYYMMDD component of the cache key if you want to force an update
      - name: Cache/restore ~/.luarocks directory
        uses: actions/cache@v2
        with:
            path: ~/.luarocks
            key: ${{ runner.os }}-cache-lua-rocks-${{ env.lua-version }}-20210912

      - name: Install luacheck
        run: |
          if [[ ! -f ~/.luarocks/bin/luacheck ]]; then
            luarocks --local install luacheck
          fi

      - name: Install lua-format
        run: |
          if [[ ! -f ~/.luarocks/bin/lua-format ]]; then
            luarocks --local install --server=https://luarocks.org/dev luaformatter
          fi

      - name: Lint sources
        run: ./build.sh -v run-linter

      - name: Run tests
        run: ./build.sh -v run-tests

      - name: Run format checks
        run: ./build.sh -v check-formatter